### ISSUE TITLE
Transfer tslint to eslint

### ISSUE THREAD

**Issue by WenheLI** [NHibiki/pm5-cli#3]
@DaKoala has mentioned that the tslint is gonna deprecate, we should move to eslint.

**Comment by DaKoala** [comment]
I will do the transferring and FYI, https://github.com/palantir/tslint
> :warning: __TSLint will be deprecated some time in 2019__. See this issue for more details: [Roadmap: TSLint &rarr; ESLint](https://github.com/palantir/tslint/issues/4534). If you're interested in helping with the TSLint/ESLint migration, please check out our [OSS Fellowship](https://medium.com/palantir/fellowships-for-open-source-developers-3892e6b75ee1) program.

**Comment by DaKoala** [comment]
migration done https://github.com/NHibiki/pm5-cli/pull/12
